Add repos as an input to the action
amitgupta7/ghas-reports-action pull request #31
Opened 2022-02-09 07:29 UTC by rohitnb

### What does this branch do?

- The action now has an additional input parameter - `repo`. This input is not mandatory and defaults to the calling repository
- Modifications were required for the action.yml and the invoke-action.yml to demo how it would work

### Intended use-case

- Allow security personnel to fetch reports for any repository by passing repo's as an input. This makes it easier for them too.

2022-02-09 07:29 UTC, rohitnb commented on action.yml
> +    default: ${{ github.repository }}
Still need to test if this default value is accepted. Forgot to test this.

2022-02-09 10:00 UTC, rohitnb commented on action.yml
> +    default: ${{ github.repository }}
It is.

2022-02-14 06:51 UTC, amitgupta7 requested changes
not required.

2022-02-14 07:39 UTC, amitgupta7 commented
@rohitnb I needed to clean-up some conditional code. So I have taken the liberty to create a separate [check-in ](https://github.com/amitgupta7/ghas-reports-action/commit/c7e27cb22c1dd2e390f42a331908e5acd44df493) Have also created a new [release](https://github.com/amitgupta7/ghas-reports-action/releases/tag/v3.4) for testing this change.

2022-02-14 07:39 UTC, closed without merging